In [3]:
import numpy as np
import matplotlib.pyplot as plt
from collections import Counter
import texttable as tt

In [4]:
def read_file(filename):
    with open(filename,'r') as fm:
        lines=[f[:-1] for f in fm.readlines()]
    return lines

In [5]:
mvratings=read_file('hw8_ratings.txt')
mvnames=read_file('hw8_movies.txt')
mlen=(len(mvnames))

In [6]:
def split_lines(mvlist):
    output=[]
    for entry in mvlist:
        output.append(entry.split(' '))
    return output

In [7]:
mvr=split_lines(mvratings)

In [8]:
def movie_ratings(mvindex,mvrates):
    smvratings=[x[mvindex] for x in mvrates]
    agg_rating=Counter(smvratings)
    #print(agg_rating)
    return agg_rating['1']/(agg_rating['0']+agg_rating['1']),smvratings  

In [9]:
rec_ratio=[]
for i in range(0,len(mvnames)):
    agg,smvratings=movie_ratings(i,mvr)
    rec_ratio.append(agg)

In [10]:
d={x:y for x,y in zip(mvnames,rec_ratio)}
sorted_mv_rec=sorted(d, key=d.__getitem__)


In [11]:
tab=tt.Texttable()
tab.header(['Movie Name','Ratio'])
for x in sorted_mv_rec:
    row=[x,d[x]]
    tab.add_row(row)
tab.set_cols_align(['c','c'])
s=tab.draw()
print(s)

+----------------------------------------------+-------+
|                  Movie Name                  | Ratio |
+==============================================+=======+
|              The_Last_Airbender              | 0.211 |
+----------------------------------------------+-------+
|             Fifty_Shades_of_Grey             | 0.360 |
+----------------------------------------------+-------+
|                I_Feel_Pretty                 | 0.381 |
+----------------------------------------------+-------+
|                  Magic_Mike                  | 0.429 |
+----------------------------------------------+-------+
|                 Man_of_Steel                 | 0.526 |
+----------------------------------------------+-------+
|              The_Shape_of_Water              | 0.562 |
+----------------------------------------------+-------+
|                 World_War_Z                  | 0.562 |
+----------------------------------------------+-------+
|                   Hustlers   

In [10]:
probZ=read_file('hw8_probZ_init.txt')
probR=read_file('hw8_probR_init.txt')

In [11]:
def split_space(arr):
    pbZ=[]
    for val in arr:
        pbZ.append(float(val.split('   ')[1]))
    return pbZ

In [12]:
pbZ=split_space(probZ)
print(pbZ)

[0.25, 0.25, 0.25, 0.25]


In [13]:
pbR=np.zeros((76,4))
for i,val in enumerate(probR):
    pbR[i,0:5]=val.split('   ')[1:5]
    #print(val.split('   ')[1:5])

In [18]:
total=len(mvratings)
pbZ=np.array(pbZ)
pbZ=pbZ.reshape((-1,1))
pbRzero=1-pbR
print(pbRzero)

[[0.5640051  0.97407377 0.45033752 0.56467761]
 [0.5796322  0.66966518 0.79535137 0.38072903]
 [0.70034533 0.73317272 0.37886617 0.47085791]
 [0.86542005 0.48642188 0.81556013 0.21466485]
 [0.14602471 0.50576316 0.15343851 0.92035452]
 [0.49475391 0.9347135  0.57187767 0.90346908]
 [0.87284003 0.40325469 0.773988   0.89305432]
 [0.77969379 0.65017371 0.53221252 0.79825677]
 [0.35959327 0.51693016 0.49476328 0.61310735]
 [0.20636255 0.41999582 0.8377014  0.29924765]
 [0.03544892 0.49999164 0.11047994 0.65838635]
 [0.43285587 0.57245404 0.56325274 0.22344082]
 [0.46439583 0.04625777 0.45579184 0.91790508]
 [0.6336576  0.1491495  0.59372496 0.97279763]
 [0.75282276 0.93285563 0.00614799 0.02941969]
 [0.19974165 0.39818288 0.23504014 0.83077455]
 [0.70697677 0.47593312 0.64337572 0.95432103]
 [0.01684655 0.55864508 0.49599956 0.67645868]
 [0.74025525 0.61311011 0.1679831  0.26325294]
 [0.62078943 0.98698266 0.20259506 0.7306112 ]
 [0.41731511 0.97444906 0.33779798 0.61247657]
 [0.5029262  

In [19]:
in1=[]
in0=[]
for rating in mvratings:
    in1.append([i for i,x in enumerate(rating.split(' ')) if x=='1'])
    in0.append([i for i,x in enumerate(rating.split(' ')) if x=='0'])
print(np.sum(pbR[in1[0],0:4],axis=0))

[21.97943023 19.58009705 21.59717806 22.04591755]


In [20]:
print(np.prod(pbR[in1[0],0]))

1.3001573294815525e-20


In [95]:
#likelihood of the tth student rating
def lhood_student_rating(pbZ,pbR,mvratings,pbRzero,student_index,z_index):
    in1=[]
    in0=[]
    for rating in mvratings:
        in1.append([i for i,x in enumerate(rating.split(' ')) if x=='1'])
        in0.append([i for i,x in enumerate(rating.split(' ')) if x=='0'])
    sm=0
    zsave=[]
    for i,pb in enumerate(pbZ):
        zprod=pb*np.prod(pbR[in1[student_index],i])*np.prod(pbRzero[in0[student_index],i])
        #print(pb)
        if(i in z_index):
            zsave.append(zprod)
        sm+=zprod
    return sm,np.array(zsave),in1,in0#list(set(range(0,76))-set(in1)-set(in0))

In [24]:
for i in range(0,258):
    sm,zsave,in1,in0=lhood_student_rating(pbZ,pbR,mvratings,pbRzero,i,[0])
    print(sm)

[8.73074141e-34]
[7.80810596e-09]
[5.54154557e-22]
[4.8703311e-19]
[1.14707307e-10]
[1.26249918e-15]
[2.21365017e-13]
[9.98294798e-07]
[1.18706864e-15]
[2.98001525e-15]
[2.22982899e-11]
[1.12633725e-06]
[1.62398245e-05]
[1.24894272e-17]
[2.27158977e-13]
[8.04044137e-15]
[1.39068091e-07]
[9.09367639e-07]
[3.80053659e-19]
[3.50591719e-18]
[3.74774343e-17]
[3.32258116e-21]
[8.03771864e-17]
[2.25096628e-06]
[1.2435208e-07]
[3.42249885e-11]
[9.25963857e-10]
[2.63176097e-09]
[1.18684417e-10]
[3.10772673e-06]
[2.15181469e-11]
[1.47832716e-18]
[3.96763181e-12]
[4.52536733e-14]
[4.51757575e-17]
[1.01531611e-14]
[9.01026548e-14]
[0.08719738]
[0.0154715]
[5.39653179e-19]
[1.26051107e-15]
[7.7472484e-12]
[5.67441229e-18]
[2.01064136e-12]
[1.21787125e-16]
[2.09836956e-14]
[8.07786177e-11]
[4.39545764e-10]
[2.95291725e-06]
[1.89490339e-17]
[6.8480366e-22]
[2.52975536e-06]
[6.68802312e-21]
[4.0442772e-11]
[3.22509991e-12]
[3.49429623e-09]
[1.55573343e-10]
[8.44113852e-13]
[1.18134162e-07]
[6.60375044

In [26]:
def llhood(pbZ,pbR,mvratings,pbRzero,total,z_index):
    lsm=0
    for i in range(0,total):
        sm,zsave,in1,in0=lhood_student_rating(pbZ,pbR,mvratings,pbRzero,i,z_index)
        #print(sm)
        lsm+=np.log(sm)
    return lsm/total 

In [27]:
ans=llhood(pbZ,pbR,mvratings,pbRzero,total,[0])
print(ans)

[-29.32759382]


In [96]:
def e_step(pbZ,pbR,mvratings,pbRzero,student_index,z_index):
    sm,zsave,in1,in0=lhood_student_rating(pbZ,pbR,mvratings,pbRzero,student_index,z_index)
    #print(zsave)
    return zsave/sm,in1,in0

In [49]:
ans,in1,in0=e_step(pbZ,pbR,mvratings,pbRzero,4,[0,1,2,3])
#print(sm)
print(ans)

[9.99320650e-01 4.08923504e-04 2.63539624e-04 6.88706990e-06]


In [103]:
def m_step(pbZ,pbR,mvratings,pbRzero,total):
    newpbZ=np.zeros(pbZ.shape).reshape((-1,1))
    #newpbR=np.zeros(pbR.shape)
    #smbz=np.zeros(pbZ.shape)
    #smbr=np.zeros(pbR.shape)
    one_sum=np.zeros(pbR.shape)
    zero_sum=np.zeros(pbR.shape)
    question_sum=np.zeros(pbR.shape)
    for i in range(0,total):
        pZr,in1,in0=e_step(pbZ,pbR,mvratings,pbRzero,i,range(0,4))
        #print(in1[0])
        newpbZ+=pZr.reshape((4,1))
        inquestion=list(set(range(0,76))-set(in1[i])-set(in0[i]))
        #print(inquestion)
        #print('indices ',inquestion)
        one_sum[in1[i],0:4]+=pZr.reshape((1,4))
        #print(in0[i])
        #zero_sum[in0[i],0:4]+=pZr.reshape((1,4))
        question_sum[inquestion,0:4]+=pZr.reshape((1,4))*pbR[inquestion,0:4]
    numerator=question_sum+one_sum
    #print('num ',numerator)
    denominator=newpbZ
    #print('den ',denominator)
    #print('new prob Z ',newpbZ)
    return newpbZ/total,numerator/denominator.reshape((1,4))

In [109]:
pbZ=split_space(probZ)
pbZ=np.array(pbZ)
pbR=np.zeros((76,4))
for i,val in enumerate(probR):
    pbR[i,0:4]=val.split('   ')[1:5]
print(pbR)
ans1,ans2=m_step(pbZ,pbR,mvratings,1-pbR,total)
print('ans1: ',ans1)
print('ans2; ',ans2)

[[0.4359949  0.02592623 0.54966248 0.43532239]
 [0.4203678  0.33033482 0.20464863 0.61927097]
 [0.29965467 0.26682728 0.62113383 0.52914209]
 [0.13457995 0.51357812 0.18443987 0.78533515]
 [0.85397529 0.49423684 0.84656149 0.07964548]
 [0.50524609 0.0652865  0.42812233 0.09653092]
 [0.12715997 0.59674531 0.226012   0.10694568]
 [0.22030621 0.34982629 0.46778748 0.20174323]
 [0.64040673 0.48306984 0.50523672 0.38689265]
 [0.79363745 0.58000418 0.1622986  0.70075235]
 [0.96455108 0.50000836 0.88952006 0.34161365]
 [0.56714413 0.42754596 0.43674726 0.77655918]
 [0.53560417 0.95374223 0.54420816 0.08209492]
 [0.3663424  0.8508505  0.40627504 0.02720237]
 [0.24717724 0.06714437 0.99385201 0.97058031]
 [0.80025835 0.60181712 0.76495986 0.16922545]
 [0.29302323 0.52406688 0.35662428 0.04567897]
 [0.98315345 0.44135492 0.50400044 0.32354132]
 [0.25974475 0.38688989 0.8320169  0.73674706]
 [0.37921057 0.01301734 0.79740494 0.2693888 ]
 [0.58268489 0.02555094 0.66220202 0.38752343]
 [0.4970738  

In [117]:
lhood=[]
pbZ=split_space(probZ)
pbZ=np.array(pbZ)
probR=read_file('hw8_probR_init.txt')
pbR=np.zeros((76,4))
for i,val in enumerate(probR):
    pbR[i,0:4]=val.split('   ')[1:5]
lhood.append(llhood(pbZ,pbR,mvratings,pbRzero,total,[0]))
for i in range(0,256):
    pbZ,pbR=m_step(pbZ,pbR,mvratings,1-pbR,total)
    ans=llhood(pbZ,pbR,mvratings,1-pbR,total,[0,1,2,3])
    print(i)
    #print(ans)
    lhood.append(ans)
anslhood={i:x for i,x in enumerate(lhood)}

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255


In [124]:
indexlist=[0 if i==-1 else 2**i for i in range(-1,9)]
#indexlist=[0,1,2,4,5,]
tab=tt.Texttable()
tab.header(['iteration','log-likelihood'])
for x in indexlist:
    row=[x,str(anslhood[x])]
    tab.add_row(row)
tab.set_cols_align(['c','c'])
s=tab.draw()
print(s)

+-----------+----------------+
| iteration | log-likelihood |
+===========+================+
|     0     |    -29.328     |
+-----------+----------------+
|     1     | [-18.13928372] |
+-----------+----------------+
|     2     | [-16.17129923] |
+-----------+----------------+
|     4     | [-14.94164271] |
+-----------+----------------+
|     8     | [-14.21071932] |
+-----------+----------------+
|    16     | [-13.85805133] |
+-----------+----------------+
|    32     | [-13.76396518] |
+-----------+----------------+
|    64     | [-13.73983093] |
+-----------+----------------+
|    128    | [-13.73771683] |
+-----------+----------------+
|    256    | [-13.73749791] |
+-----------+----------------+


In [125]:
for i in indexlist:
    print('the index: ' +str(i)+' log-likelihood: '+str(anslhood[i]))

the index: 0 log-likelihood: -29.327593818611266
the index: 1 log-likelihood: [-18.13928372]
the index: 2 log-likelihood: [-16.17129923]
the index: 4 log-likelihood: [-14.94164271]
the index: 8 log-likelihood: [-14.21071932]
the index: 16 log-likelihood: [-13.85805133]
the index: 32 log-likelihood: [-13.76396518]
the index: 64 log-likelihood: [-13.73983093]
the index: 128 log-likelihood: [-13.73771683]
the index: 256 log-likelihood: [-13.73749791]


In [130]:
cl_id=read_file('hw8_ids.txt')
my_id_in=cl_id.index('A53272054')

In [131]:
post_prob,in1,in0=e_step(pbZ,pbR,mvratings,1-pbR,my_id_in,range(0,4))

In [138]:
print(post_prob)
#print(in1[my_id_in])
#print(in0[my_id_in])
inquestion=list(set(range(0,76))-set(in1[my_id_in])-set(in0[my_id_in]))
val=np.round(np.sum(pbR[inquestion,0:4]*post_prob.reshape((1,4)),axis=1),0)
print(val)

[[6.73629137e-04]
 [1.18230888e-94]
 [0.00000000e+00]
 [9.99326371e-01]]
[0, 1, 3, 7, 10, 21, 26, 30, 31, 32, 37, 39, 47, 59, 65]
[8, 20, 36, 43, 45, 50]
[1. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0.
 1. 1. 0. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0.
 0. 1. 1. 1. 0. 1. 1.]


In [142]:
indexlist=inquestion
tab.header(['Movie Name','Predicted Rating'])
tab=tt.Texttable()
for i,x in enumerate(indexlist):
    row=[mvnames[x],str(val[i])]
    tab.add_row(row)
tab.set_cols_align(['c','c'])
s=tab.draw()
print(s)

+----------------------------------------------+---+
|                  Black_Swan                  | 1 |
+----------------------------------------------+---+
|              The_Last_Airbender              | 0 |
+----------------------------------------------+---+
| Harry_Potter_and_the_Deathly_Hallows:_Part_1 | 1 |
+----------------------------------------------+---+
|                  Iron_Man_2                  | 0 |
+----------------------------------------------+---+
|                     Thor                     | 0 |
+----------------------------------------------+---+
| Harry_Potter_and_the_Deathly_Hallows:_Part_2 | 1 |
+----------------------------------------------+---+
|                  Bridemaids                  | 1 |
+----------------------------------------------+---+
|       The_Girls_with_the_Dragon_Tattoo       | 1 |
+----------------------------------------------+---+
|              X-Men:_First_Class              | 1 |
+---------------------------------------------